import { prefixPluginTranslations } from "@strapi/helper-plugin";
import pluginPkg from "../../package.json";
import pluginId from "./pluginId";
import Initializer from "./components/Initializer";
import PluginIcon from "./components/PluginIcon";
//import Slug from "./components/Input";

const name = pluginPkg.strapi.name;

export default {
  register(app) {

    // app.addFields([
    //   { type: 'custom-slug', Component: Slug },
    // ]);

    app.addMenuLink({
      to: `/plugins/${pluginId}`,
      icon: PluginIcon,
      intlLabel: {
        id: `${pluginId}.plugin.name`,
        defaultMessage: name,
      },
      Component: async () => {
        const component = await import(
          /* webpackChunkName: "[request]" */ "./pages/App"
        );

        return component;
      },
      permissions: [
        // Uncomment to set the permissions of the plugin here
        // {
        //   action: '', // the action name should be plugin::plugin-name.actionType
        //   subject: null,
        // },
      ],
    });

    app.customFields.register({
      name: "slug",
      pluginId: "custom-slug",
      type: "string",
      intlLabel: {
        id: "custom-slug.form.label",
        defaultMessage: "slug",
      },
      intlDescription: {
        id: "custom-slug.form.description",
        defaultMessage: "Autogenerated Custom Slug",
      },
      icon: PluginIcon,
      components: {
        Input: async () =>
          import(
            /* webpackChunkName: "input-component" */ "./components/Input"
          ),
      },
      options: {
        base: [
          {
            sectionTitle: {
              id: 'custom-slug.form.kw',
              defaultMessage: 'Default Value',
            },
            items: [ // Add settings items to the section
              {
                intlLabel: {
                  id: 'custom-slug.form.kw.label',
                  defaultMessage: 'Change KW "post" inside the placeholder: post-${y}-${m}-${d}-${h}-${min}-${s}',
                },
                name: 'options.kw',
                type: 'string'
              },
            ]
          },
          {
            sectionTitle: {
              id: 'custom-slug.form.pattern',
              defaultMessage: 'Slug Pattern',
            },
            items: [ // Add settings items to the section
              {
                intlLabel: {
                  id: 'custom-slug.form.pattern.label',
                  defaultMessage: 'Create a slug alias pattern'
                },
                name: 'options.pattern',
                type: 'select',
                options: [
                  {
                    key: 'title',
                    value: 'title',
                    metadatas: {
                      intlLabel: {
                        id: 'custom-slug.form.pattern.title',
                        defaultMessage: 'title',
                      },
                    },
                  },
                  {
                    key: 'id',
                    value: 'id',
                    metadatas: {
                      intlLabel: {
                        id: 'custom-slug.form.pattern.id',
                        defaultMessage: 'id',
                      },
                    },
                  },
                  {
                    key: 'datetime',
                    value: 'datetime',
                    metadatas: {
                      intlLabel: {
                        id: 'custom-slug.form.pattern.datetime',
                        defaultMessage: 'datetime',
                      },
                    },
                  },

                ],
              },
            ]
          }
        
        ],
      }
    });

    app.registerPlugin({
      id: pluginId,
      initializer: Initializer,
      isReady: false,
      name,
    });
  },

  bootstrap(app) { },
  async registerTrads({ locales }) {
    const importedTrads = await Promise.all(
      locales.map((locale) => {
        return import(
          /* webpackChunkName: "translation-[request]" */ `./translations/${locale}.json`
        )
          .then(({ default: data }) => {
            return {
              data: prefixPluginTranslations(data, pluginId),
              locale,
            };
          })
          .catch(() => {
            return {
              data: {},
              locale,
            };
          });
      })
    );

    return Promise.resolve(importedTrads);
  },
};
