/*
 *
 * HomePage
 *
 */

import React from 'react';
// import PropTypes from 'prop-types';
import pluginId from '../../pluginId';

const HomePage = () => {
  return (
    <div>
      <h1>{pluginId} plugin</h1>
      <p>This is Autogenerated Custom Field plugin which generates rewritable values, like: post-year-month-day-hours-minutes-seconds and saves the same value for all locales in slug.</p>
      <ul>
        <li> autocomplete uniq default value </li>
        <li> same slug value to all locales </li>
        <li> rewritable data </li>
        <li> different patterns value to autofill slug field placeholder </li>
      </ul>
    </div>
  );
};

export default HomePage;
